// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.8.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

int calculatePower({required int base, required int exponent}) => RustLib
    .instance
    .api
    .crateApiSimpleCalculatePower(base: base, exponent: exponent);

PlatformInt64 calculateFibonacci({required int n}) =>
    RustLib.instance.api.crateApiSimpleCalculateFibonacci(n: n);

Int32List sortLargeArray({required int size}) =>
    RustLib.instance.api.crateApiSimpleSortLargeArray(size: size);

List<Int32List> matrixMultiplication({required int size}) =>
    RustLib.instance.api.crateApiSimpleMatrixMultiplication(size: size);
